name: Testes com Robot Framework e SeleniumLibrary

on: [push, pull_request]

jobs:
  test-apis:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_reports_dir: 'robot_tests/reports'
        robot_tests_dir: 'robot_tests/api'
      
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: robot-reports
        path: robot_tests/reports

  test-interfaces:
    runs-on: ubuntu-latest  
    needs: test-apis
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_reports_dir: 'robot_tests/reports'
        robot_tests_dir: 'robot_tests/interface'
      
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: robot-reports-interfaces
        path: robot_tests/reports

        